# Session variables:
SESSION_PERMANENT: str = "SESSION_PERMANENT"

# SQL Alchemy variables:
SQLALCHEMY_DATABASE_URI: str = "SQLALCHEMY_DATABASE_URI"
SQLALCHEMY_TRACK_MODIFICATIONS: str = "SQLALCHEMY_TRACK_MODIFICATIONS"

